apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: rajeshtalla0209/votingapp-worker:1
        name: vote
        ports:
        - containerPort: 80
          name: vote
